### ISSUE TITLE
Blackjack - MC prediction - sample policy

### ISSUE THREAD

**Issue by yb1989** [dennybritz/reinforcement-learning#127]
sample policy function has bad return

return np.array([1.0, 0.0]) if score >= 20 else np.array([0.0, 1.0])

should be:
return 0 if score >= 20 else 1

**Comment by jonahweissman** [comment]
@yb1989 Good point! Looks like this was fixed in PR #137. Do you mind closing this issue?

**Comment by dennybritz** [comment]
👍  I'll close this. Thanks for checking @jonahweissman
