### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by fferreres** [dennybritz/reinforcement-learning#13]
I am not sure how to send a comment, but I found your code VERY readable, almost like reading english, how it's structured also very beautiful, the names of every variable make sense. It's also highly appreciated that you follow the same terminology as David and Richard in a pristine way, and that due to AIGym, the code is just very focused. But you also put the right comments.

Also, the README has great resources, very up to date and relevant. I didn't know about many of them. And the learning objectives and summary is very good as a refresh of the long reads (book) or David slides.

I hope you find enough time and energy to complete some of the algorithms that are missing! Thank you so much for sharing your work!

**Comment by kaspermarstal** [comment]
Totally agree. And while I use TensorFlow almost exclusively now, I have always disliked reading TensorFlow code and have found it difficult to settle on a coding style. Until now. TensorFlow should be written as you do.

**Comment by dennybritz** [comment]
Thanks! Yeah I'll definitely add the missing algorithms, I just have a deadline coming up and didn't have much time the past 2-3 weeks. Should be coming in the next few weeks though!

**Comment by IbrahimSobh** [comment]
I do agree, Thanks for your keen efforts and well documented repo.
