### ISSUE TITLE
How does the implementation of epsilon-greedy MC control algorithm update the policy?

### ISSUE THREAD

**Issue by kdu4108** [dennybritz/reinforcement-learning#132]
In the comments of the solution for "MC Control with Epsilon-Greedy Policies Solution", it's stated that "the policy is improved implicitly by changing the Q dictionary". While I see how changing the Q dictionary reveals to you which actions in which states will yield the optimal value (and the "implicit" optimal policy is just to make the action that maximizes this value in every state), the code also returns a policy--but this looks to me to be the same arbitrary initial policy since that policy itself is never updated in the loop, only the Q dictionary.

Could someone explain to me how/when (what line(s) of code would be especially great) the policy is improving so that the evaluation->improvement->evaluation->... cycle works in this implementation? Thanks!

**Comment by chaonan99** [comment]
I think in this implementation the policy is a function which gets evaluated with the latest Q value every time you call it. So the only thing you need to do is to update the Q dictionary.

**Comment by kdu4108** [comment]
I see, so do you mean in order to return your "optimal" policy you need to call make_epsilon_greedy_policy after the Q dictionary has been updated the final time?

However, I'm still confused. If I'm understanding the MC control algorithm correctly, it operates by **generalized policy iteration**, which is the cycle in which: 
a policy is evaluated to create Q-value table --> policy is improved from this Q-value table with epsilon-greedy --> this improved policy is evaluated to create a new Q-value table --> ...

But, it seems in this implementation while every episode involves the policy evaluation, there is no policy improvement and it is always using the same policy from the beginning?

**Comment by chaonan99** [comment]
No you don't have to. Once you called `make_epsilon_greedy_policy` the `policy` is **linked** with the Q dict. The `policy` in this implementation is only a function. You need to convince yourself that every time you call `policy(some_state)` it's using the latest Q dict already (This seems like pointer in C++, the `policy` function stores a pointer pointing to the location of Q dict, not a separate copy of Q, so once you update Q, `policy` also gets updated simultaneously).

That is to say,

1. You don't have to call `make_epsilon_greedy_policy ` again in the end;
2. Policy do improves when Q gets updated

**Comment by kdu4108** [comment]
Ah thank you for the explanation, that makes sense.
