### ISSUE TITLE
CliffWalk REINFORCE Comments

### ISSUE THREAD

**Issue by IbrahimSobh** [dennybritz/reinforcement-learning#14]
Dear

Thanks for your keen efforts.

1- I think the comments below are misleading (These comments could belong to Q-Learning not to REINFORCE)

def **reinforce**(env, estimator_policy, estimator_value, num_episodes, discount_factor=1.0):
    """
    Q-Learning algorithm for fff-policy TD control using Function Approximation.
    Finds the optimal greedy policy while following an epsilon-greedy policy.
    
    Args:
        env: OpenAI environment.
        estimator: Action-Value function estimator
        num_episodes: Number of episodes to run for.
        discount_factor: Lambda time discount factor.
        epsilon: Chance the sample a random action. Float betwen 0 and 1.
        epsilon_decay: Each episode, epsilon is decayed by this factor
    
    Returns:
        An EpisodeStats object with two numpy arrays for episode_lengths and episode_rewards.
    """

**Comment by dennybritz** [comment]
Thanks for pointing this out, I will fix the comments.
