### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by PilgrimYuan** [dennybritz/reinforcement-learning#140]
Every time when I run the code, it raises NotImplementedError from the code ‘state=env.reset()’. Could you please tell me how to fix it ?

**Comment by tankconcordia** [comment]
Thank you very much for contacting me.

Would you mind let me know where on my code this error occur?

Thank you,
Best regards,

Yingcong Tan

**Comment by tankconcordia** [comment]
I just checked my code in colab, it works fine.

Here is the link to my colab code:
https://drive.google.com/file/d/1wxWptrmQubBOYlKNXPCbqjdtLcImayRb/view?usp=sharing

If it is possible, I can come to your office and run the code on my laptop.

thank you very much,
Sorry for the inconveniences.
Best regards,

Yingcong Tan

Thank you,

Best regards,

Yingcong Tan

**Comment by wenbowen123** [comment]
The same. Anyone could help is highly appreciated!

**Comment by wenbowen123** [comment]
@PilgrimYuan BTW, did you solve the problem?

**Comment by dennybritz** [comment]
I merged the PR, closing for now!
