### ISSUE TITLE
Epsilon Greedy Policy functions returns policies with slightly wrong probabilities

### ISSUE THREAD

**Issue by filipolszewski** [dennybritz/reinforcement-learning#142]
As I wrote first in the closed Issue #114 :
The method used in solution of MC Control excersise (and not only!) produces slightly wrong probabilities. For epsilon = 0.010 and 10 actions, best action has 0.001 + 1.000 - 0.010 = 0.991 and not 0.990 probability. I believe that the code proposed by @HanfengChi in the #114 Issue gives the correct probs.

As I am a newcomer to the field (and open-source/GitHub interaction), I might be wrong - if so, I apologize for the confusion and I'd be glad to hear the explanation. But if I'm right, I'm up for working on the pull request with the adjustment to the code in all the notebooks with this issue.

**Comment by dennybritz** [comment]
Yes, I think that's right! If you submit a Pull Request I will merge it :)

**Comment by filipolszewski** [comment]
I spent some time wondering and it actually may be fine the way it is. 0.991 probability means 0.99 of the time the best action is chosen *greedily*, but 0.001 of the times, the best action is chosen out of all actions *due to the random move.*

I don't remember any mention in literature about excluding the best action from the set of possible random move actions, so I think we rushed it a bit and I should close the issue.

**Comment by HanfengChi** [comment]
I think when agent performs random actions,it should include the best action.Otherwise,the best action would not be selected when epsilon equals 1. So I closed my issue.

**Comment by filipolszewski** [comment]
Yes, exactly. Thank you! Closing the issue now :)

**Comment by filipolszewski** [comment]
Just for clarification to anyone wondering about the answer/correct way, on page 22nd of Sutton's book, it is mentioned that for 10 actions and epsilon = 0.1, probability of choosing the best action is in fact 91%.
