### ISSUE TITLE
Unclear what gather_indices holds

### ISSUE THREAD

**Issue by aneesh297** [dennybritz/reinforcement-learning#151]
In ` reinforcement-learning/DQN/dqn.py` it's not exactly clear how in line 95 we "Get the predictions for the chosen actions only". Could you please elaborate on this?

**Comment by ArikVoronov** [comment]
The two lines 95-96 go together:
'
gather_indices = tf.range(batch_size) * tf.shape(self.predictions)[1] + self.actions_pl
self.action_predictions = tf.gather(tf.reshape(self.predictions, [-1]), gather_indices)
`

predictions are a matrix with dimensions [samples,actions]
tf.reshape(self.predictions, [-1]) flattens the prediction matrix to a single vector with dim [samples*actions]
You want to gather the prediction values corresponding to actions that were actually performed in each sample to difference from the target. To get those predictions from the flattened vector you need a bunch of flattened indices, which is what gather_indices gives you.

example, 5 samples:
predictions.shape = [5,4] ([samples,actions])
flattened_predictions.shape = tf.reshape(self.predictions, [-1]).shape = [20] (*I gave it a name, its not explicit in the code)
actions_pl = [1,0,2,1,3]
 tf.range(batch_size) * tf.shape(self.predictions)[1] = [0,1,2,3,4]*4 = [0,4,8,12,16]
gather_indices =[0,4,8,12,16] + actions_pl = [1,4,10,13,19]

so now you gather actions indexed by the above from the flattened vector. For example, the 3rd index in gather_indices is 10, which in flattened_predictions corresponds to action 2 in sample 3.

I think with the way tf.gather works you could do the same action without gather_indices or flattening, but I didn't want to mess with it.

**Comment by aneesh297** [comment]
Thanks for the answer!
