### ISSUE TITLE
Does anyone know why I can not import lib in jupyter notebook?

### ISSUE THREAD

**Issue by wenqiao534** [dennybritz/reinforcement-learning#152]

**Comment by wenqiao534** [comment]
When I perform the ipnb,that is an error in the first cell.Dose anyone else met with this situation?Or anyone has a solution of sloving this problem,thanks!

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-5b257857b497> in <module>()
     11 if "../" not in sys.path:
     12   sys.path.append("../")
---> 13 from lib.envs.cliff_walking import CliffWalkingEnv
     14 from lib import plotting
     15 

ModuleNotFoundError: No module named 'lib.envs'

**Comment by chaonan99** [comment]
Are you using Windows?

**Comment by honglonggiao** [comment]
I downloaded the folder "lib" and copy to Jupyter running directory. 
Rename lib to libRL. 
Import:
from libRL.envs.gridworld import GridworldEnv
It operated!

**Comment by Nittur** [comment]
Change lib to Lib(capital 'L') after checking if the libraries exist.

**Comment by iseegr8tfuldeadppl** [comment]
I know this isn't your issue but for the people who had my same problem, you'll find the lib folder [here](https://github.com/dennybritz/reinforcement-learning/).
