### ISSUE TITLE
Policy Evaluation Solution VS Sutton's Page 75

### ISSUE THREAD

**Issue by benjamintanweihao** [dennybritz/reinforcement-learning#171]
In the Sutton book, the iterative policy evaluation is:
![policy_iteration](https://user-images.githubusercontent.com/861236/43047393-457c58fa-8e09-11e8-9846-72335326997c.png)

I'm confused about the `v <- V[s]` because when I compare this to the implementation:

```python
    while True:
        delta = 0
        # For each state, perform a "full backup"
        for s in range(env.nS):
            v = 0 # <--- Why is this v = 0 instead of v = V[s]
            # Look at the possible next actions
            for a, action_prob in enumerate(policy[s]):
                # For each action, look at the possible next states...
                for  prob, next_state, reward, done in env.P[s][a]:
                    # Calculate the expected value. Ref: Sutton book eq. 4.6.
                    v += action_prob * prob * (reward + discount_factor * V[next_state])
            # How much our value function changed (across any states)
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
```

Why is it `v = 0` instead of `v = V[s]`?

**Comment by dennybritz** [comment]
The old `V(s)` is only used to compute the delta. In the book, they cache the old value of `V(s)` in `v`., update `V(s)` and compute delta. I do the opposite. I put the new value of `V(s)` into `v`, and compute the delta, and then update `V(s)`. It is the same computation, just the code organization is different.

It could be that the code is written based on the lecture slides, not the book.
