### ISSUE TITLE
policy evaluation algorithm and implementation bug

### ISSUE THREAD

**Issue by Hamifthi** [dennybritz/reinforcement-learning#177]
hello every body i'm just learning reinforcement learning recently and i think policy evaluation has a bug
i mean this algorithm:
![image](https://user-images.githubusercontent.com/21039345/46259531-8f920100-c4e7-11e8-900c-02a8726c2cd3.png)
exactly the line that we calculate delta value.
the problem is the first round that V values calculated, the delta is max of zero that we initialized and max value of V values so the delta become the v value. but the next round that we calculate the V values, the delta is max of previous delta and new max value of V values, but the problem is because of coverage of V values the absolute subtraction of new V values and previous V values has lower values from the delta from the previous round and as a result the delta remain the same as previous and the loop becomes infinite loop.
i myself act in another way to solve the problem, if i misunderstand this i'm glad if someone could explain it to me.

**Comment by ArikVoronov** [comment]
The first line in the main while loop (outside of the states loop) is delta = 0 : 
![image](https://user-images.githubusercontent.com/43729836/46325126-8c8a3400-c5ff-11e8-963d-093bc8759f73.png)

The line max(delta,v-V(s)) inside the states loop is only about comparing value differences between states of each iteration.

**Comment by Hamifthi** [comment]
I don't pay attention to that and that's right so i have one more question is this algorithm the most optimal way to solve this problem from the point of view of time consuming?

**Comment by ArikVoronov** [comment]
Not 100% sure, but I think in simple cases like this value iteration is more efficient.
It makes sense since you update your policy at every step instead of converging on values for some arbitrary policy and only then updating your policy.

**Comment by Hamifthi** [comment]
My point wasn't about policy iteration vs value iteration, actually i want to know that this algorithm specifically is efficient from the point of view of big o notation or O(), because i have another solution and i want to know that which one is better.

**Comment by blackpredator** [comment]
thanks!!

Em ter, 2 de out de 2018 às 07:58, Hamed Fathi <notifications@github.com>
escreveu:

**Comment by Hamifthi** [comment]
The problem solved and i close this issue
