### ISSUE TITLE
MC Off-policy solution fixes

### ISSUE THREAD

**Issue by fferreres** [dennybritz/reinforcement-learning#19]
I think there are two typos in MC off-policy code with solutions, regarding the target policy.

--current code--
    def policy_fn(observation):
        A = np.zeros_like(Q[state], dtype=float)
        best_acton = np.argmax(Q[state])
        A[best_action] = 1.0
        return A
    return policy_fa
-- end --

1. Var "best_acton" should be "best_action"
2. argument "observation" should be named "state"

**Comment by dennybritz** [comment]
Thanks!
