### ISSUE TITLE
Randomness in optimal epsilon_greedy_policy 

### ISSUE THREAD

**Issue by levindabhi** [dennybritz/reinforcement-learning#196]
Why we are not decaying epsilon in epsilon_greedy_policy ?

**Comment by apoorvagnihotri** [comment]
@levindabhi I am not sure but isn't it a type of a hyperparameter? If you would like to decay it, then you can else you can just assume that the minimum \epsilon allowed is the \epsilon you gave to the algorithm in the first place.
