### ISSUE TITLE
Experience Replay and Targets Network

### ISSUE THREAD

**Issue by IbrahimSobh** [dennybritz/reinforcement-learning#2]
Dear 

Fist of all, Thank you so much for  this great work!

Regarding: reinforcement-learning/FA/Q-Learning with Value Function Approximation Solution.ipynb

The approximator is trained on **correlated samples** from the online environment. My question is: Will this affect the training process? slowing it down or making it un-stable? 

Should we use Experience Replay (and maybe Target Network)? or there is no need, and why?

Thank you and best regards
Sobh

**Comment by dennybritz** [comment]
I believe experience replay may improve the result but in practice a **linear** function approximator seems to work fine even without experience replay, like you see in the example. I don't think there's theory that proves that it converges though (I may be wrong).

Once you use a more complex approximator like a Neural Network this becomes a problem and you need Experience Replay (or some other way to decorrelate samples like asynchronous agents). If you look at the DQN example, it does have experience replay.
