### ISSUE TITLE
Why CliffWalkingEnv returns 'is_done=True' when reaching cliff?

### ISSUE THREAD

**Issue by wakamori** [dennybritz/reinforcement-learning#219]
Hi, author!
Thank you for sharing such a great repository.

I have a question about your implementation of [CliffWalkingEnv](https://github.com/dennybritz/reinforcement-learning/blob/master/lib/envs/cliff_walking.py).

Maybe the original definition of Cliff Walking is 'Example 6.6: Cliff Walking' of [1].
It implies that the episodes of Cliff Walking will end when and only when the agent reaches G(goal).

[1] Sutton, Richard S., and Andrew G. Barto. "Reinforcement learning: An introduction." (2011). The second edition's pdf is published [here](http://www.incompleteideas.net/book/RLbook2018.pdf).

I confirmed that OpenAI Gym's [CliffWalkingEnv](https://github.com/openai/gym/blob/master/gym/envs/toy_text/cliffwalking.py) is implemented as describe above.

However, if my understanding is not wrong, your implementation of CliffWalkingEnv seems to that the episodes will end when the agent reaches both Cliff and Goal.

The relevant part is Line 27 in cliff_walking.py

https://github.com/dennybritz/reinforcement-learning/blob/06ce3127a2cb7cfd6cf2a9cbd523ac4550db5a54/lib/envs/cliff_walking.py#L27

My question is:
- Is my understanding of the ending states of your CliffWalkingEnv correct?
- If it is true, why the difference exists?

Again, thank you for providing a great repository.
It is really helpful for understanding the RL algorithms.

Regards,

**Comment by makaveli10** [comment]
is_done is True whenever the episode terminates. Either by reaching the cliff or by successfully completing the episode.

**Comment by wakamori** [comment]
Hi @makaveli10! Thank you for your comment.

I understand that the answer is as follows:

- Is my understanding of the ending states of your CliffWalkingEnv correct?
  - Correct.
- If it is true, why the difference exists?
  - Difference in implementation. At this implementation, both by reaching the cliff and by successfully completing the episode are treated as termination.

Thanks!
