### ISSUE TITLE
n-step

### ISSUE THREAD

**Issue by fferreres** [dennybritz/reinforcement-learning#22]
Denny, is there any particular reason you are not including n-step methods? Any plans or interest in them? Or maybe about Eligibility Traces.

**Comment by dennybritz** [comment]
There's no particular reason, I thought implementing the other algorithms is higher priority. It's definitely on the TODO list though, just not at the top ; )

**Comment by fferreres** [comment]
Awesome, so we'll just have to be patient then :-)
