### ISSUE TITLE
SARSA vs TD in FA question

### ISSUE THREAD

**Issue by fferreres** [dennybritz/reinforcement-learning#23]
Denny, in the [Function Approx](https://github.com/dennybritz/reinforcement-learning/blob/master/FA/Q-Learning%20with%20Value%20Function%20Approximation%20Solution.ipynb) you have created the TD targets for both SARSA (commented out) and Q-Learning, but it may escape many people that you can't just uncomment the lines and comment the Q-Learning to make it SARSA but you also need to change the last assignment so SARSA sticks to the next_action it chose in the commented out code in the next step iteration, while Q-Learning discards it (ie. no change from what it does right now)

Does this make sense to you?

Hacky (ugly) version of what I mean:

        next_action = None 
        # One step in the environment
        for t in itertools.count():            
            # Take a step
            if (next_action == None):
                # print("I am doing Q-Learning")
                action_probs = policy(state)
                action = np.random.choice(np.arange(len(action_probs)), p=action_probs)
            else:
                # print("I am doing SARSA")
                action = next_action

**Comment by dennybritz** [comment]
That makes sense. I agree this is confusing and I didn't pay attention to that. I'll change it. Thanks for reporting!
