### ISSUE TITLE
A3C actions

### ISSUE THREAD

**Issue by fferreres** [dennybritz/reinforcement-learning#24]
Denny, I just saw the merge of all the a3c goodies. This is really so exciting. I am not going to look at the code until I review the simpler ones because it's too awesome. However -and if I am testing to early no worries just discard- I am trying it out with Breakout-v0:

./train.py --model_dir /tmp/a3c --env Breakout-v0 --t_max 10 --eval_every 30 --parallelism 2 --reset

And every video seems to only have the action "right" or "do nothing" working. It never seems to try "left" even once. I tried resetting 3 times, and have run about 5k, 12k and now at 4k and all videos up into 32 (longest run) all have "right" (and very seldom "nothing") as the only action.

I am not sure how tensorboard works, but it only ever shows worker_0/ (in addition to eval/). Not sure if it should show as many workers as cpus I assign (I tried assigning 2 and 4). 

The a3c code seems to be shaping beautifully.

**Comment by dennybritz** [comment]
Ah yeah, I made some last minute changes without checking. #469fed1ba0f8b6f8f45a0e767373a403ec4680cf should fix it .

> I am not sure how tensorboard works, but it only ever shows worker_0/ (in addition to eval/). Not sure if it should show as many workers as cpus I assign (I tried assigning 2 and 4).

This is correct. The summaries for all the workers are pretty much identical, so I disabled summaries for all workers except the first one to save disk space.

**Comment by fferreres** [comment]
Awesome, fixed. I am training Breakout. Will probably spend the next month learning your a3c implementation (after learning DQN). I will close since fix. Happy week! (I am loving this thing).
