### ISSUE TITLE
image_resize()

### ISSUE THREAD

**Issue by fferreres** [dennybritz/reinforcement-learning#29]
In DQN.py (and the notebook)an error is raised and the fix is to provide the new size as an array with2 scalars). Now:
```
self.output = tf.image.resize_images(
                self.output, 84, 84, method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)
```
... but it wants:
```
self.output = tf.image.resize_images(
                self.output, [84, 84], method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)
```

**Comment by fferreres** [comment]
I am not sure if this only happens in TensorBoard 0.11 and [master]. Maybe they changed this part? If others are not seeing this it could be version specific.

**Comment by dennybritz** [comment]
Ah yeah, this was an API change in the new Tensorflow version.

**Comment by IbrahimSobh** [comment]
Dear fferreres, 
The same issue was mentioned here 
https://github.com/dennybritz/reinforcement-learning/issues/26

> 2- Moreover, I had to upgrade to TensorFlow 0.11 and Cuda 8.0

and it worked fine

**Comment by DanielTakeshi** [comment]
As a gentle reminder, this issue still exists in Deep Q Learning Solution.ipynb, in the `StateProcessor` class.
