### ISSUE TITLE
SARSA and Value Function Approximation

### ISSUE THREAD

**Issue by IbrahimSobh** [dennybritz/reinforcement-learning#3]
Dear

Regarding:

reinforcement-learning/FA/Q-Learning with Value Function Approximation Solution.ipynb

and regarding the commented code:

> SARSA TD Target for on policy-training
> next_action_probs = policy(next_state)
> next_action = np.random.choice(np.arange(len(next_action_probs)), p=next_action_probs)             
> td_target = reward + discount_factor * q_values_next[next_action]
> 

I think you want to say that: it is ok to use SARSA instead of Q-Learning in this specific example. 

However, In case of non linear approximator (neural network as in DQN), we usually use reply memory to break the correlation. Using reply memory will limit us with off-policy algorithms (such as Q-learning), and we can not/should not use on-policy algorithms (such as SARSA) while using reply-memory. (I believe the reason is that: When using reply memory, the sampled transitions used for policy update taken from the reply-memory, are actually generated using old-version of the policy not the current version)

**If this is correct,** then the commented code may work, only because in this specific code, you are using a simple linear approximator and not using reply memory, **correct?**

Thank you     
Final note: I cannot wait for the A3C implementation  :)

**Comment by dennybritz** [comment]
> I think you want to say that: it is ok to use SARSA instead of Q-Learning in this specific example.

I left the code there to demonstrate the SARSA and Q-Learning is almost the same, except for a small change in the code.

> However, In case of non linear approximator (neural network as in DQN), we usually use reply memory to break the correlation. Using reply memory will limit us with off-policy algorithms (such as Q-learning), and we can not/should not use on-policy algorithms (such as SARSA) while using reply-memory. (I believe the reason is that: When using reply memory, the sampled transitions taken from the reply-memory are actually generated using old-version of the policy not the current version)

Yes, I believe this is correct. You cannot use replay memory with on-policy algorithms. However, you can use asynchronous mehtods (like A3C) that break correlations with on-policy algorithms.

> then the commented code may work, only because in this specific code, you are using a simple linear approximator and not using reply memory, correct?

Yes, SARSA still works because I am not using a replay memory.
