### ISSUE TITLE
TypeError: resize_images()

### ISSUE THREAD

**Issue by nanxintin** [dennybritz/reinforcement-learning#35]
Dear all,
I have some trouble when running the code, here is the debug information:
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    max_global_steps=FLAGS.max_global_steps)
  File "/home/sk/sk/reinforcement-learning-master-new/PolicyGradient/a3c/worker.py", line 76, in __init__
    self.sp = StateProcessor()
  File "/home/sk/sk/reinforcement-learning-master-new/lib/atari/state_processor.py", line 15, in __init__
    self.output, [84, 84], method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)
TypeError: resize_images() takes at least 3 arguments (3 given)
It means the arguments numbers are not correct. But I can not solve it.
Could anyone give me some suggestions?

**Comment by IbrahimSobh** [comment]
I faced the same problem, It was solved after upgrading to TensorFlow 0.11

**Comment by fferreres** [comment]
Yes. If you don't want to upgrade just remove the brackets on the arguments [84,84]

**Comment by nanxintin** [comment]
@IbrahimSobh @fferreres Thank you for your help.
