### ISSUE TITLE
A3C: Score and Performance

### ISSUE THREAD

**Issue by Astrych** [dennybritz/reinforcement-learning#37]
Hi!,
I've made some long running tests and here are the results:

![benchmark_2](https://cloud.githubusercontent.com/assets/8657975/20788298/79a96f0e-b7b0-11e6-85a0-ead1de834203.png)

![benchmark_1](https://cloud.githubusercontent.com/assets/8657975/20788259/52a78daa-b7b0-11e6-923e-a99471a119a5.png)

![benchmark_3](https://cloud.githubusercontent.com/assets/8657975/20788309/7f8942b4-b7b0-11e6-8e52-1fe410ecb363.png)

As you can see the score plateaus too quickly. In addition, the performance does not improve with the increase of threads number...

**Comment by dennybritz** [comment]
Check out this issue: https://github.com/dennybritz/reinforcement-learning/issues/30 - It's most likely the same problem so I'm closing this for now.
