### ISSUE TITLE
Paper Investigation

### ISSUE THREAD

**Issue by andrewcz** [dennybritz/reinforcement-learning#4]
Hi Denny!,
Big Fan!
Was wondering if you had any thoughts about reproducing this paper for one
of your tutorials.
https://arxiv.org/abs/1603.01121.
Just super interested in this specific topic.
Many thanks,
Andrew

**Comment by dennybritz** [comment]
Thanks! I haven't read the paper yet, it's on my reading list though. I'll definitely add something about the paper once I've read it!
