### ISSUE TITLE
Action repeat in Atari environments

### ISSUE THREAD

**Issue by Shadowen** [dennybritz/reinforcement-learning#40]
Are there any plans to implement action repeat in Atari environments? In the original DQN paper, they repeated each action taken by the network for 4 frames instead of asking the network for an action every frame. This is supposed to improve the training time without sacrificing (much) performance, since Atari does not require frame-perfect inputs anyways.

I tried to add this. I saw **faster wall-clock training time** but **decreased final performance** (possibly issue #30)? Any ideas? I can run a few more experiments (though these take about a day each run for me) and set up a pull request if you think this is good.

**Comment by dennybritz** [comment]
I think OpenAI gym already comes with action repeat: https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py

**Comment by Shadowen** [comment]
Wow, that's convenient! Though I think it defaults to [2,5]...
