### ISSUE TITLE
A3C results peak at only ~22 reward

### ISSUE THREAD

**Issue by IbrahimSobh** [dennybritz/reinforcement-learning#41]
Dear Denny

I would like to share the results of A3C code.  (after more than 5 Million steps)

![breakout_a3c](https://cloud.githubusercontent.com/assets/19908396/20880885/6f971414-bae2-11e6-9f96-dd0885dde2e0.PNG)

![breakout_a3c_small](https://cloud.githubusercontent.com/assets/19908396/20881026/09c54e48-bae3-11e6-81a7-52f19d570a06.PNG)

![breakout_a3c_details](https://cloud.githubusercontent.com/assets/19908396/20880912/924c01a4-bae2-11e6-8097-c1a950837a67.PNG)
 
What do you think went wrong?

Regards

**Comment by dennybritz** [comment]
Thanks for sharing. See https://github.com/dennybritz/reinforcement-learning/issues/37 and https://github.com/dennybritz/reinforcement-learning/issues/30 - Still figuring out...

**Comment by IbrahimSobh** [comment]
Thanks Denny 
I will close this issue for now ...
