### ISSUE TITLE
GPU misuse

### ISSUE THREAD

**Issue by camigord** [dennybritz/reinforcement-learning#43]
Hello Denny,
thanks a lot for all the code you have made available. I have been trying to implement a DQN myself using tensorflow, but I have noticed (also when testing your code) that during training only a small fraction of the GPU is used (around 10-15%). This is of course not very efficient and I do not see how this is going to be better than using a CPU... Do you have any thoughts on this?

I am training using a Titan X and with the current progress I estimate it will take me a little more than a week to train the model as described in the original paper. 

Please let me know what do you think about all this.

**Comment by dennybritz** [comment]
Hi,
Hi,

Thanks for reporting. What exactly do you mean by 15% of usage? Is it 15% of memory of 15% of time is spent on the GPU? If it's memory - I think that's expected. The network used in DQN is extremely small, so even with a larger batch size it will only use a bit of the GPU memory that's available.

If most of the **time** is spent on the CPU that's another issue and probably worth looking into. In that case it would be good to figure out where the bottleneck is. For example, the Atari emulator has to be run on the CPU, so does the "main loop", etc.

**Comment by camigord** [comment]
Hi, thanks for replying so fast.
yeah, I was talking about memory usage. I agree it should be expected... I guess it is just a little disappointing. 

I will be testing some code I am writing based on your approach and the code provided by [carpedm20](https://github.com/carpedm20/deep-rl-tensorflow) and I will report the results when finish training. I am also interested on implementing some other models and techniques (such as double Q, prioritized mem. replay etc etc), so I guess you will be hearing from me in the near future.

Thanks again for your help.
