### ISSUE TITLE
A3C: estimators.py

### ISSUE THREAD

**Issue by IbrahimSobh** [dennybritz/reinforcement-learning#45]
**Line 17** 

Comment Three convolutional layers  

I think it should be Two convolutional layers 

**Line 24:** 

fc1 = tf.contrib.layers.fully_connected(
    inputs=tf.contrib.layers.flatten(conv2),
    num_outputs=256,
    scope="fc1")

I think we should add: 
activation_fn=tf.nn.relu

**Comment by dennybritz** [comment]
Hi,

> I think it should be Two convolutional layers

Yep.

> I think we should add:
> activation_fn=tf.nn.relu

I think the default is ReLU so you don't need to add it. But it adding it would definitely look nicer and make it more explicity.

Feel free to submit a pull request and I'll merge it 👍
