### ISSUE TITLE
ImportError: No module named atari

### ISSUE THREAD

**Issue by loveJasmine** [dennybritz/reinforcement-learning#49]
rzai@rzai00:/media/rzai/ai_data/prj/reinforcement-learning/PolicyGradient/a3c$ python train.py 
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from lib.atari import helpers as atari_helpers
ImportError: No module named atari

**Comment by camigord** [comment]
Are you sure you downloaded the entire repository? Denny placed that file [here](https://github.com/dennybritz/reinforcement-learning/blob/master/lib/atari/helpers.py).

**Comment by loveJasmine** [comment]
with python3

rzai@rzai00:/media/rzai/ai_data/prj/reinforcement-learning/PolicyGradient/a3c$ python3 train.py
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
[2017-01-04 20:40:12,464] Making new env: Breakout-v0
Traceback (most recent call last):
  File "train.py", line 76, in <module>
    policy_net = PolicyEstimator(num_outputs=len(VALID_ACTIONS))
  File "/media/rzai/ai_data/prj/reinforcement-learning/PolicyGradient/a3c/estimators.py", line 89, in __init__
    tf.summary.merge(self.loss.op.name, self.loss)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/summary/summary.py", line 285, in merge
    val = _gen_logging_ops._merge_summary(inputs=inputs, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 227, in _merge_summary
    result = _op_def_lib.apply_op("MergeSummary", inputs=inputs, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 406, in apply_op
    (input_name, op_type_name, values))
TypeError: Expected list for 'inputs' argument to 'MergeSummary' Op, not global/policy_net/loss.
rzai@rzai00:/media/rzai/ai_data/prj/reinforcement-learning/PolicyGradient/a3c$ vim train.py

**Comment by camigord** [comment]
Looks like a problem with the Tensorflow version. Which version do you have installed?

**Comment by loveJasmine** [comment]
tf11

**Comment by andytwigg** [comment]
I think there is a missing `__init__.py` file here. You can do `$ touch lib/atari/__init__.py` and try again.
