### ISSUE TITLE
discount_factor is unused

### ISSUE THREAD

**Issue by rianrajagede** [dennybritz/reinforcement-learning#55]
In Montecarlo prediction and control, when calculating G you are not using discount_factor, shouldn't it written:

```
...
G = sum([x[2]*(discount_factor**i) for i,x in enumerate(episode[first_occurence_idx:]]))
...
```

**Comment by rockingdingo** [comment]
@rianrajagede  Hi I also found this and I think your code should mean  '])])' instead of ']]))',  right?
@dennybritz  any thought?
e.g.
...
G = sum([x[2]*(discount_factor**i) for i,x in enumerate(episode[first_occurence_idx:])])
...
