### ISSUE TITLE
I have a ImportError.... Could you help me ?

### ISSUE THREAD

**Issue by wonchul-kim** [dennybritz/reinforcement-learning#62]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-06cc8d6dc545> in <module>()
     12   sys.path.append("../")
     13 
---> 14 from lib import plotting
     15 from collections import deque, namedtuple

ImportError: No module named 'lib'

When I follow the case for 'Deep Q-learning for atari game', there happened this error...

What should I do>??
( I'm using python3 on Ubuntu 14.04 LTS and jupyter notebook)

**Comment by dennybritz** [comment]
Make sure you start the Notebook server from the right directory. I think it should be started in the root directory of the repo.
