### ISSUE TITLE
typo in Continuous MountainCar Actor Critic Solution.ipynb ?

### ISSUE THREAD

**Issue by ricky1203** [dennybritz/reinforcement-learning#78]
in file Continuous MountainCar Actor Critic Solution.ipynb class PolicyEstimator 
the action is used as placeholder: 
    self.action = tf.placeholder(dtype=tf.float32, name="action")
but in following code:
    self.action = self.normal_dist._sample_n(1)

something wrong ?

**Comment by dennybritz** [comment]
Yes, the placeholder is not necessary. I fixed in a commit.
