### ISSUE TITLE
maybe something wrong in DP

### ISSUE THREAD

**Issue by XiaolongMeng** [dennybritz/reinforcement-learning#79]
v += action_prob * prob * (reward + discount_factor * V[next_state])
this line maybe:
v += action_prob * (reward + discount_factor * prob*V[next_state])

In my understanding,the prob is the environment probability,so it should multiply next state.

**Comment by XiaolongMeng** [comment]
I know what is going on....

**Comment by liziniu** [comment]
My opinion is the same as yours. 
I also think that line should be :
v += action_prob * (reward + discount_factor * prob*V[next_state])
