### ISSUE TITLE
Small Error in DQN

### ISSUE THREAD

**Issue by junhyeokahn** [dennybritz/reinforcement-learning#89]
Hi,
First of all, I appreciate your kindness of maintaining this great project.
When I was trying DQN playground, I get this error below
```
    print(env.get_action_meanings())
AttributeError: 'TimeLimit' object has no attribute 'get_action_meanings'
```
Also, I tried after just commenting out that line. I was able to reach to the end but the rendering was not maintained. It just exit.

I would appreciate if you could help me.
Thanks

**Comment by seandevs** [comment]
@junhyeokahn try changing...

`print(env.get_action_meanings())` --> `print(env.unwrapped.get_action_meanings())`
