### ISSUE TITLE
Broken link for "Reinforcement Learning: An Introduction"

### ISSUE THREAD

**Issue by RandallJEllis** [dennybritz/reinforcement-learning#91]
Looks like Sutton moved his website to http://incompleteideas.net/sutton/index.html and the chapter linked to (along with a complete draft of the book) has been moved here: http://incompleteideas.net/sutton/book/the-book-2nd.html

**Comment by jaidmin** [comment]
amazing! thanks a lot, I was working with the August 2016 Draft and some parts were missing.

**Comment by dennybritz** [comment]
Thank you, I updated the link.
